-- Schema for the OrthodoxWiki scraper.
-- Applied automatically on startup, but provided here for reference / manual setup.

CREATE TABLE IF NOT EXISTS pages (
    pageid          BIGINT       PRIMARY KEY,          -- MediaWiki page id
    title           TEXT         NOT NULL,
    url             TEXT         NOT NULL,
    namespace       INTEGER      NOT NULL DEFAULT 0,
    revid           BIGINT,                            -- latest revision id we stored
    content         TEXT,                              -- wikitext of the page
    content_length  INTEGER,
    categories      TEXT[]       NOT NULL DEFAULT '{}', -- categories this page belongs to
    page_touched    TIMESTAMPTZ,                       -- MediaWiki "touched" timestamp
    first_seen      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_seen       TIMESTAMPTZ  NOT NULL DEFAULT now(), -- last time we observed it in a category
    last_crawled    TIMESTAMPTZ,                       -- last time we fetched its content
    removed_at      TIMESTAMPTZ,                       -- set when the wiki confirms the page is gone (NULL = active)
    media_paths     TEXT[]       NOT NULL DEFAULT '{}', -- local paths of media downloaded for this page
    contributors    TEXT[]       NOT NULL DEFAULT '{}', -- page authors, for attribution
    attribution     TEXT,                              -- ready-to-use credit line (CC BY-SA / GFDL)
    UNIQUE (title)
);

-- Migrations for databases created before these columns existed.
ALTER TABLE pages ADD COLUMN IF NOT EXISTS removed_at TIMESTAMPTZ;
ALTER TABLE pages ADD COLUMN IF NOT EXISTS media_paths TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE pages ADD COLUMN IF NOT EXISTS contributors TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE pages ADD COLUMN IF NOT EXISTS attribution TEXT;

CREATE INDEX IF NOT EXISTS pages_last_crawled_idx ON pages (last_crawled);
CREATE INDEX IF NOT EXISTS pages_categories_idx   ON pages USING GIN (categories);
-- Speeds up the per-run "what did we not see this time" reconciliation query.
CREATE INDEX IF NOT EXISTS pages_active_idx ON pages (last_seen) WHERE removed_at IS NULL;

-- Downloaded media files live on disk (content-addressed by sha1 under the
-- configured download_dir); the DB never stores the bytes. pages.media_paths
-- lists each page's files, and this table records one row per file with its
-- redistribution level (derived from the file's license tags).
CREATE TABLE IF NOT EXISTS media (
    media_id        TEXT         PRIMARY KEY,          -- sha1 (or url-hash fallback)
    title           TEXT,                              -- e.g. "File:Saint_Nicholas.jpg"
    local_path      TEXT,
    mime            TEXT,
    source_url      TEXT,
    license_name    TEXT,                              -- most permissive recognized license
    redistribution  TEXT         NOT NULL DEFAULT 'prohibited'
        CHECK (redistribution IN ('public', 'free', 'restricted', 'prohibited')),
    first_seen      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_seen       TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS media_redistribution_idx ON media (redistribution);


-- ============================================================================
-- Icon & Saints data layer (PRD: "Orthodox Icon & Saints Data Layer").
--
-- A licensed, multi-source layer feeding a consumer feature set (search/save/
-- follow saints & icons). HARD CONSTRAINT: nothing is ever served unless it
-- passed the license gate. Every content-bearing row carries source +
-- license + attribution; icons only reach crawl_status = 'approved' via the
-- gate in license_gate.py. The app layer must query WHERE crawl_status =
-- 'approved' (quarantined/rejected rows are retained for audit only).
-- ============================================================================

-- One row per ingest source (met_api, wikimedia, iconsaint, ...). base_license
-- is the source-level grant; requires_per_item_check distinguishes per-object
-- checks (Met/Wikimedia) from a blanket grant (ICONSAINT). Editing base_license
-- invalidates cached approvals for that source (see reflag on next run).
CREATE TABLE IF NOT EXISTS sources (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                    TEXT NOT NULL UNIQUE,
    base_license            TEXT NOT NULL,
    attribution_template    TEXT,
    requires_per_item_check BOOLEAN NOT NULL DEFAULT TRUE,
    last_verified_at        TIMESTAMPTZ,
    notes                   TEXT,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Saints. feast_day / bio_* are nullable until a verified-licensed text source
-- is wired in (open risk in the PRD); bio_text must NOT be served while
-- bio_license IS NULL.
CREATE TABLE IF NOT EXISTS saints (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_name  TEXT NOT NULL UNIQUE,
    alt_names       TEXT,                              -- JSON array, for search
    feast_day       TEXT,                              -- MM-DD, nullable
    bio_text        TEXT,
    bio_source_id   BIGINT REFERENCES sources(id),
    bio_license     TEXT,                              -- NULL = do not serve bio_text
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS icons (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saint_id              BIGINT REFERENCES saints(id),
    title                 TEXT NOT NULL,
    image_url             TEXT,                        -- local/CDN copy, never hotlinked
    image_source_id       BIGINT NOT NULL REFERENCES sources(id),
    image_license         TEXT NOT NULL,               -- denormalized for fast filtering
    attribution_text      TEXT NOT NULL,               -- rendered, ready to display
    description           TEXT,
    description_source_id BIGINT REFERENCES sources(id),
    veneration_date       TEXT,                        -- MM-DD, nullable
    source_record_id      TEXT,                        -- original id in source system
    crawl_status          TEXT NOT NULL DEFAULT 'pending_license_check'
        CHECK (crawl_status IN ('pending_license_check','approved','quarantined','rejected')),
    quarantine_reason     TEXT,                        -- why the gate withheld it
    local_path            TEXT,                        -- content-addressed file on disk
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (image_source_id, source_record_id)         -- idempotent re-ingest
);
CREATE INDEX IF NOT EXISTS icons_status_idx ON icons (crawl_status);
CREATE INDEX IF NOT EXISTS icons_saint_idx  ON icons (saint_id);

-- User-facing tables. Auth/account fields are out of scope (PRD §8); only the
-- columns the crawl + notification pipelines touch are modeled here.
CREATE TABLE IF NOT EXISTS users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS favorites (
    user_id     BIGINT NOT NULL REFERENCES users(id),
    icon_id     BIGINT NOT NULL REFERENCES icons(id),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, icon_id)
);

CREATE TABLE IF NOT EXISTS follows (
    user_id     BIGINT NOT NULL REFERENCES users(id),
    target_type TEXT NOT NULL CHECK (target_type IN ('saint','icon')),
    target_id   BIGINT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, target_type, target_id)
);
CREATE INDEX IF NOT EXISTS follows_target_idx ON follows (target_type, target_id);

-- Recurring events (feast/nameday/veneration, matched on MM-DD) and one-off
-- events (new_icon_added, matched on the full created_at date). The UNIQUE key
-- keeps event generation idempotent.
CREATE TABLE IF NOT EXISTS events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_type TEXT NOT NULL CHECK (target_type IN ('saint','icon')),
    target_id   BIGINT NOT NULL,
    event_type  TEXT NOT NULL
        CHECK (event_type IN ('feast_day','nameday','veneration_day','new_icon_added')),
    event_date  TEXT,                                  -- MM-DD recurring, full date one-off
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (target_type, target_id, event_type, event_date)
);
CREATE INDEX IF NOT EXISTS events_date_idx ON events (event_type, event_date);

-- Human-reviewed approvals/rejections that override the automated gate (e.g. an
-- archdiocese page cleared after explicit permission). Auditable and kept
-- separate from automated decisions.
CREATE TABLE IF NOT EXISTS license_overrides (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name      TEXT NOT NULL,
    source_record_id TEXT NOT NULL,
    decision         TEXT NOT NULL CHECK (decision IN ('approved','rejected')),
    license          TEXT,
    attribution      TEXT,
    reviewer         TEXT,
    reason           TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source_name, source_record_id)
);

CREATE TABLE IF NOT EXISTS notifications_sent (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id),
    event_id    BIGINT NOT NULL REFERENCES events(id),
    sent_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS notifications_user_event_idx ON notifications_sent (user_id, event_id);
